#!/bin/sh

set -e

echo "BAMBOO_AGENT_VERSION:         $AGENT_VERSION"
echo "BAMBOO_SERVER_HOST:           $BAMBOO_SERVER_HOST"
echo "BAMBOO_SERVER_PORT:           $BAMBOO_SERVER_PORT"
echo "BAMBOO_SERVER_PRE_SHARED_KEY: $BAMBOO_SERVER_PRE_SHARED_KEY"

CONNECTION_STRING="http://${BAMBOO_SERVER_HOST}:${BAMBOO_SERVER_PORT}/agentServer/"
AGENT_URL="http://${BAMBOO_SERVER_HOST}:${BAMBOO_SERVER_PORT}/agentServer/agentInstaller/"
AGENT_INSTALLER_FILENAME="atlassian-bamboo-agent-installer-${AGENT_VERSION}.jar"

wget -nv $AGENT_URL -O $AGENT_INSTALLER_FILENAME

if [ -z "${BAMBOO_SERVER_PRE_SHARED_KEY}" ]; then
  echo "-> Starting Bamboo Agent."
  java -jar $AGENT_INSTALLER_FILENAME $CONNECTION_STRING
else
  echo "-> Starting Bamboo Agent with pre-shared key."
  java -jar $AGENT_INSTALLER_FILENAME $CONNECTION_STRING -t $BAMBOO_SERVER_PRE_SHARED_KEY
fi
